targets:
  $default:
    builders:
      database_system|toSQLGeneratorBuilder:
        enabled: True
        generate_for:
          - lib/**/*

builders:
  toSQLGeneratorBuilder:
    import: 'package:database_system/generators/generators.dart'
    builder_factories: ['toSQLGeneratorBuilder']
    auto_apply: dependents
    build_extensions: {".dart": [".sql.part"]}
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]